lang: es
timezone: Europe/Madrid

title: Portfolio de Ciberseguridad
tagline: Writeups de máquinas vulnerables
description: Resolución de máquinas vulnerables. Contenido educativo.

url: "https://juan-perez-ortega.github.io"

github:
  username: Juan-Perez-Ortega

social:
  name: Juan Perez Ortega
  links:
    - https://github.com/Juan-Perez-Ortega

theme_mode: dark

paginate: 10

toc: true

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed
