lang: es
timezone: Europe/Madrid

title: Portfolio de Ciberseguridad
tagline: Writeups de máquinas vulnerables
description: Resolución de máquinas vulnerables. Contenido educativo.

url: "https://juan-perez-ortega.github.io"

github:
  username: Juan-Perez-Ortega

social:
  name: Juan Perez Ortega
  links:
    - https://github.com/Juan-Perez-Ortega

theme: jekyll-theme-hacker

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      permalink: /posts/:title/
  - scope:
      path: ""
      type: pages
    values:
      layout: default

